let moviesData = [];
let currentFilter = "all";
let currentSearch = "";
let visibleCount = 12;
let allMovies = [];
async function loadMoviesData(){try{const r=await fetch("data/movies.json",{cache:"no-store"});moviesData=await r.json();allMovies=Array.isArray(moviesData)?moviesData:[];renderMovies()}catch(e){const g=document.getElementById("moviesGrid");if(g)g.innerHTML='<div class="no-results">Failed to load movies</div>'}}
function renderMovies(){const g=document.getElementById("moviesGrid");if(!g)return;let f=allMovies.filter(m=>{if(currentFilter!=="all"&&!(m.genres||[]).includes(currentFilter))return false;if(currentSearch){const t=(m.title||"").toLowerCase(),te=(m.title_en||"").toLowerCase(),q=currentSearch.toLowerCase();if(!t.includes(q)&&!te.includes(q))return false}return true});const s=f.slice(0,visibleCount);g.innerHTML=s.length?s.map(m=>`<div class="movie-card" onclick="location.href='movie/${m.id}.html'"><img src="${m.poster}" alt="${m.title}" loading="lazy"><div class="movie-card-info"><h3>${m.title}</h3><p>${m.title_en||""}</p><div class="movie-meta"><span>⭐ ${m.rating}</span><span>🎬 ${m.year}</span></div></div></div>`).join(''):'<div class="no-results">No movies found</div>';const b=document.getElementById('loadMoreBtn');if(b)b.style.display=visibleCount>=f.length?'none':'inline-flex'}
function initSite(){document.querySelectorAll('.cat-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.cat-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');currentFilter=btn.dataset.cat||"all";visibleCount=12;renderMovies()}));const s=document.getElementById('searchInput');if(s)s.addEventListener('input',e=>{currentSearch=e.target.value||"";visibleCount=12;renderMovies()});const l=document.getElementById('loadMoreBtn');if(l)l.addEventListener('click',()=>{visibleCount+=12;renderMovies()});loadMoviesData()}
document.addEventListener('DOMContentLoaded',initSite);
